### PR TITLE
Allow require by composer

### PR DESCRIPTION
**Pull request by dougchan-okta**

### CODE REVIEW

**Comment by benubois** [comment]
Hi Doug,

I stopped writing PHP before namespaces landed, so I had a couple questions about this.

1. What does this do?
2. For composer, does this need to be registered somewhere?
3. Do the namespace changes mean that the way the library is used/included change? If so, would you mind updating the README/code comments with the new syntax?

Thanks!

Ben

**Comment by dougchan-okta** [comment]
Hey Ben,

Sure I could definitely update the README. After you require the project via composer:

`composer require flickerbox/marketo`

The Marketo class becomes available project-wide (via composer's autoload). I'm using it for a behat automated testing project right now, but it will also open doors to other composer-based projects (like D8)

2 PHP usage examples:

Example 1:
$marketo = new Flickerbox\Marketo(...);

Example 2:
use Flickerbox\Marketo;

class MyClass {
  private $marketo;

  public __construct() {
    $this->marketo = new Marketo();
  }
}

Probably will be easier to read once I include examples in the README. No pressure to accept the pull request, but I'm glad to help if it's something that you think will improve your project!


Doug Chan

Full-stack Drupal Developer

doug.chan@okta.com

[Okta • Connect everything]<https://www.okta.com/>


________________________________

**Review by codyrobert — APPROVED** [review]
Thanks for the contrib @dougchan-okta! I'll get the readme updated

**Comment by dougchan-okta** [comment]
Thanks @codyrobert ! Did you get a chance to test it? It might need some adjustments before it works 100%. It's been a long time so I apologize if it breaks anything

**Pull request merged**
